import { QuizProvider } from './context/QuizContext'
import './App.css'
import Homepage from './components/Homepage/Homepage'
import Nav from './components/Nav'
import { Route, Routes } from 'react-router-dom'
import Category from './components/categories/Category'
import Login from './components/LoginReg/Login'
import Reg from './components/LoginReg/Reg'
import Quiz from './components/Homepage/Quiz'
// ? Add a feature to choose a category ✔️
// ? Add context for question and score ✔️
// ? Add a feature to choose the difficulty of the questions
// ? Add another harder difficulty generated by AI 
// ? Add a feature to choose the number of questions
// ? add a feature to get a hint for the question
// ? Timed rounds
// ? Login and register
// ? Add a leaderboard
// ? PVP

function App() {
  return (
    <div>
      <QuizProvider>
        <Nav />
        <Routes>
          <Route path='/' element={<Homepage/>} />
          <Route path='/quiz' element={<Quiz/>} />
          <Route path='/categories' element={<Category />} />
          <Route path='/login' element={<Login />} />
          <Route path='/register' element={<Reg />} />
        </Routes>
      </QuizProvider>
    </div>
  )
}

export default App
